strategy:
  matrix:
    windows:
      imageName: 'windows-latest'
    macOS:
      imageName: 'macOS-latest'
    linux:
      imageName: 'ubuntu-latest'

pool:
  vmImage: $(imageName)

steps:

  # Linux and macOS.
  - script: |
      set -e
      curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain stable
      export PATH=$PATH:$HOME/.cargo/bin
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: "Install rust (*nix)"
    condition: not(eq(variables['Agent.OS'], 'Windows_NT'))

  # Windows.
  - script: |
      curl -sSf -o rustup-init.exe https://win.rustup.rs
      rustup-init.exe -y --profile minimal --default-toolchain stable
      set PATH=%PATH%;%USERPROFILE%\.cargo\bin
      echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
    displayName: "Install Rust (Windows)"
    condition: eq(variables['Agent.OS'], 'Windows_NT')

  # All platforms
  - script: cargo build --all
    displayName: Cargo build

  # All platforms
  - script: cargo test --all
    displayName: Cargo test
