[package]
name = "cargo-osha"
version = "0.1.0"
authors = ["Simon Heath <icefoxen@gmail.com>", "Steven Fackler <sfackler@gmail.com>"]
license = "Apache-2.0/MIT"
description = "A small utility to count the uses of unsafe code in a Rust program."
repository = "https://github.com/icefoxen/cargo-osha"
readme = "README.md"
keywords = ["unsafe", "cargo", "plugin"]
categories = ["command-line-utilities", "development-tools", "development-tools::cargo-plugins", "parsing"]

[badges]
maintenance = { status = "as-is" }

[dependencies]
syn = {version = "0.12", features = ["parsing", "printing", "clone-impls", "full", "extra-traits", "visit"]}
clap = "2"
cargo = "0.27"
env_logger = "0.5"
failure = "0.1"
petgraph = "0.4"
structopt = "0.2"
walkdir = "2.1.4"
