[package]
name = "cargo-tree"
version = "0.15.0"
authors = ["Steven Fackler <sfackler@palantir.com>"]
license = "MIT/Apache-2.0"
description = "A Cargo subcommand that visualizes a crate's dependency graph in a tree-like format"
repository = "https://github.com/sfackler/cargo-tree"
readme = "README.md"

[dependencies]
cargo = "0.24"
env_logger = "0.4"
petgraph = "0.4"
serde = "1.0"
serde_derive = "1.0"
