[package]
authors = ["anderejd <rajder@gmail.com>"]
categories = ["command-line-utilities", "development-tools", "development-tools::cargo-plugins", "parsing"]
description = "Detects usage of unsafe Rust in your project and its dependencies."
edition = "2018"
keywords = ["unsafe", "cargo", "plugin"]
license = "Apache-2.0/MIT"
name = "cargo-geiger"
readme = "README.md"
repository = "https://github.com/anderejd/cargo-geiger"
version = "0.9.0"

[badges]
maintenance = { status = "experimental" }

[dependencies]
cargo = "0.40.0"
colored = "1.9.0"
console = "0.9.1"
env_logger = "0.7.1"
geiger = { path = "../geiger", version = "0.4.1" }
petgraph = "0.4.13"
pico-args = "0.3.0"
walkdir = "2.2.9"

[dev-dependencies]
assert_cmd = "0.11.1"
better-panic = "0.2.0"
insta = "0.12.0"
regex = "1.3.1"
rstest = "0.4.1"
