[package]
authors = ["anderejd <rajder@gmail.com>"]
categories = ["command-line-utilities", "development-tools", "development-tools::cargo-plugins", "parsing"]
description = "Detects usage of unsafe Rust in a Rust crate and its dependencies."
edition = "2018"
keywords = ["unsafe", "cargo", "plugin"]
license = "Apache-2.0/MIT"
name = "cargo-geiger"
readme = "README.md"
repository = "https://github.com/rust-secure-code/cargo-geiger"
version = "0.10.2"

[badges]
maintenance = { status = "experimental" }

[dependencies]
cargo = "0.47.0"
cargo-geiger-serde = { path = "../cargo-geiger-serde", version = "0.1.0" }
cargo_metadata = "0.12.0"
cargo-platform = "0.1.1"
colored = "2.0.0"
console = "0.11.3"
env_logger = "0.7.1"
geiger = { path = "../geiger", version = "0.4.5" }
krates = "0.5.0"
petgraph = "0.5.1"
pico-args = "0.3.3"
regex = "1.4.2"
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.57"
strum = "0.19.2"
strum_macros = "0.19.2"
walkdir = "2.3.1"
anyhow = "1.0.31"
url = "2.1.1"

[features]
vendored-openssl = ["cargo/vendored-openssl"]

[dev-dependencies]
assert_cmd = "1.0.1"
better-panic = "0.2.0"
fs_extra = "1.2.0"
insta = "0.16.1"
rand = "0.7.3"
regex = "1.3.9"
rstest = "0.6.4"
semver = "0.11.0"
tempfile = "3.1.0"
