[package]
authors = ["anderejd <rajder@gmail.com>"]
categories = ["command-line-utilities", "development-tools", "development-tools::cargo-plugins", "parsing"]
description = "Detects usage of unsafe Rust in a Rust crate and its dependencies."
edition = "2018"
keywords = ["unsafe", "cargo", "plugin"]
license = "Apache-2.0/MIT"
name = "cargo-geiger"
readme = "README.md"
repository = "https://github.com/rust-secure-code/cargo-geiger"
version = "0.11.1"

[badges]
maintenance = { status = "experimental" }

[dependencies]
anyhow = "1.0.40"
cargo = "0.52.0"
cargo-geiger-serde = { path = "../cargo-geiger-serde", version = "0.2.0" }
cargo_metadata = "0.13.1"
cargo-platform = "0.1.1"
colored = "2.0.0"
console = "0.14.1"
geiger = { path = "../geiger", version = "0.4.7" }
krates = "0.7.0"
petgraph = "0.5.1"
pico-args = "0.4.0"
regex = "1.4.5"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
strum = "0.20.0"
strum_macros = "0.23.0"
walkdir = "2.3.2"
url = "2.2.1"

[features]
vendored-openssl = ["cargo/vendored-openssl"]

[dev-dependencies]
assert_cmd = "1.0.3"
better-panic = "0.2.0"
fs_extra = "1.2.0"
insta = "1.7.1"
rand = "0.8.3"
regex = "1.4.5"
rstest = "0.7.0"
semver = "0.11.0"
tempfile = "3.2.0"
