name: "Cargo-geiger Release Builder"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        type: string

permissions:
  contents: write

jobs:

  matrix:
    name: Generate Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix-json: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: release-repo
      - id: set-matrix
        run: |
          content=`cat ./release-repo/matrix.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=matrix::$content"
  build:
    needs: [matrix]
    uses: rinse-repeat/auditable-builder/.github/workflows/rust-builder.yml@main
    with:
      repository: geiger-rs/cargo-geiger
      rust-target: ${{ matrix.rust-target }}
      os: ${{ matrix.os }}
      rust: ${{ matrix.rust }}
      use-features: ${{ matrix.use-features }}
      use-cache: true
      use-locked: true
      serial: AAB
      zig-version: 0.9.1
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.matrix.outputs.matrix-json) }}

  release:
    needs: [build]
    uses: rinse-repeat/auditable-builder/.github/workflows/release-builder.yml@main
    with:
      repository: geiger-rs/cargo-geiger
      tag: ${{ github.event.inputs.tag }}

